### ISSUE TITLE
クイズにキャリアウェーブで画像保存

### ISSUE THREAD

**Issue by furukawaeiichi** [furukawaeiichi/QUIZ_APP#152]

**Comment by furukawaeiichi** [comment]
ふと気になって試したが、れなっちS3からふるかわS3に変更したため、本番環境でもアバターの画像登録ができなくなっている。
.env のPW変えた後にデプロイ作業していないので、解決していないKeyエラーはデプロイすれば直るのかもしれない。

**Comment by fujii-kosuke-36** [comment]
クイズの画像もアップロードできないのでしょうか？
