### ISSUE TITLE
エディターに画像を直接保存するとActive Strageになるので、保存できなくする

### ISSUE THREAD

**Issue by furukawaeiichi** [furukawaeiichi/QUIZ_APP#155]
https://qiita.com/MIDO-ruby7/items/fd2c31ba00d8420cf630#%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%AE%E5%89%8A%E9%99%A4

**Comment by fujii-kosuke-36** [comment]
対応方法　どれくらい時間がかかるのか目処
