### ISSUE TITLE
「ユーザー登録必須」なことを記載する

### ISSUE THREAD

**Issue by kashiwagi-rena** [furukawaeiichi/QUIZ_APP#158]
・ユーザー登録必須なことに記載
・なんなら、みどりさんおすすめのチュートリアルしてみたい

[チュートリアルツアー](https://tourguidejs.com/)

**Comment by ayakuma309** [comment]
https://qiita.com/MIDO-ruby7/items/353e1205b5a5bc87ad92?utm_campaign=post_article&utm_medium=twitter&utm_source=twitter_share
