### ISSUE TITLE
イントロダクション簡単に作れるらしい

### ISSUE THREAD

**Issue by furukawaeiichi** [furukawaeiichi/QUIZ_APP#173]
みどりさんこれで簡単に実装できたそうです！
（僕がユーザー立場だと、イントロダクション眺めてほぼ頭に入らないです）
https://tourguidejs.com

**Comment by fujii-kosuke-36** [comment]
quizzes_indexだけで発火させたいやつがapplication.html.erbに処理書いてるんで全部のページで発火知っちゃってるんじゃないかなって推測
6/6はquizzes_indexの一番上に書いてるやつが発火してる

**Comment by fujii-kosuke-36** [comment]
7/25対応予定
