### ISSUE TITLE
デザイン再調整（ユーザー）

### ISSUE THREAD

**Issue by furukawaeiichi** [furukawaeiichi/QUIZ_APP#176]

**Comment by fujii-kosuke-36** [comment]
現状マイページでは
アバター画像
投稿したクイズの件数
プロフィール編集
投稿したクイズ一覧
追加要素としてはクイズ関連
正解率　間違えたクイズ一覧　難易度　カテゴリー等

**Comment by fujii-kosuke-36** [comment]
TOPページのデザインの変更　いい案があれば
