### ISSUE TITLE
ハンバーガーメニュー　mode切り替えを適応させる

### ISSUE THREAD

**Issue by furukawaeiichi** [furukawaeiichi/QUIZ_APP#41]
---（新:Issue内容）---
ハンバーガーメニュー
light modeなら明るく、dark modeなら暗く、mode切り替えに合わせてデザインする。

---（旧:Issue内容）---
「ハンバーガーメニュー　ライトモード時は明るくする」という内容でしたが追記してあります
light modeのcssが反映されませんでした。
原因解析して、周辺のコードも見やすくリファクタリングお願いします🙏

![Image](https://github.com/furukawaeiichi/QUIZ_APP/assets/102509805/94600ec7-9a97-46ea-8b07-976f180c1ffc)

**Comment by fujii-kosuke-36** [comment]
ダークモード対応に伴う弊害　文字が消える等の確認　全体的に

**Comment by fujii-kosuke-36** [comment]
別のタスクで対応中
